onnx_path=$1 # yolov5s onnx model path, recommend using the final opt model generated by tpu-mlir
onnx_input_name=$2 # yolov5s input name, use scripts/get_onnx_input_output.py to get it
train_img_dir=$3 # train image dir
train_bin_dir=$4 # save bin dir
train_data_number=100 # number of train data, recommend 100 or more
save_root=$5 # save root dir
calib_table=$6 # calib table path of yolov5s onnx, use tpu-mlir to generate it

# get dipoorlet data bins
python scripts/generate_data_bins.py \
    --dataset coco2017 \
    --data-root ${train_img_dir} \
    --save-root ${train_bin_dir}/${onnx_input_name}

# train dipoorlet
python -m torch.distributed.launch --master_port=29500 --use_env -m dipoorlet \
        -M ${onnx_path} -I ${train_bin_dir} \
        -N ${train_data_number} -A mse -D sophgo --brecq --drop \
        -O ${save_root} --extra_calib_table ${calib_table}